### ISSUE TITLE
Error: spawn lftp ENOENT

### ISSUE THREAD

**Issue by JohnnyPicnic** [travisghansen/node-red-contrib-lftp#6]
Running Node-RED version: v0.20.5, Node.js  version: v10.23.1, Linux 4.14.138 arm LE
This embedded so I don't have control over the versions.
Manually installed lftp and it's dependencies.
Getting Error: spawn lftp ENOENT on any command.

**Comment by travisghansen** [comment]
Sounds like the lftp binary isn’t in the PATH?

**Comment by JohnnyPicnic** [comment]
I need some help with how to fix that.

**Comment by travisghansen** [comment]
Where did you place the binary on the fs?

**Comment by JohnnyPicnic** [comment]
/opt/ with a sym link to /usr/lib/node_modules/
I'm following the instructions given here:
https://icr.advantech.cz/support/faq/detail/building-the-custom-nodes-for-node-js-node-red

**Comment by travisghansen** [comment]
That’s where you placed the lftp binary or this project?

**Comment by JohnnyPicnic** [comment]
The device doesn't have the palette manager so I installed the node by placing it in /opt with a link to /usr/lib/node_modules/node-red/nodes
Then restart Node-Red. If all the dependencies are met then the node installs. 
Don't know if this helps:
2021-10-26 13:43:47 [info] Settings file  : /usr/lib/node_modules/node-red/settings.js
2021-10-26 13:43:47 [info] Context store  : 'default' [module=memory]
2021-10-26 13:43:47 [info] User directory : /usr/lib/node_modules/node-red
2021-10-26 13:43:47 [info] Projects disabled : user settings
2021-10-26 13:43:47 [info] Flows file     : /var/data/node-red/flows.json

**Comment by travisghansen** [comment]
There are 2 things that need to be installed:

1. the lftp binary (usually installed using the system package manager)
2. this plugin

I think you’ve successfully done the latter but have missed the first step.

**Comment by JohnnyPicnic** [comment]
Thanks for the help. The os doesn't have a package manager but the do provide a way to install custom Apps (user modules).

**Comment by travisghansen** [comment]
You are likely stuck then :( as pre-requesite this module depends on the `lftp` binary.

**Comment by JohnnyPicnic** [comment]
Yes I believe I am. Thank again for your help.
